Document: pgbackup
Title: Debian pgbackup Manual
Author: <insert document author here>
Abstract: This manual describes what pgbackup is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pgbackup/pgbackup.sgml.gz

Format: postscript
Files: /usr/share/doc/pgbackup/pgbackup.ps.gz

Format: text
Files: /usr/share/doc/pgbackup/pgbackup.text.gz

Format: HTML
Index: /usr/share/doc/pgbackup/html/index.html
Files: /usr/share/doc/pgbackup/html/*.html
